### ISSUE TITLE
Create a form and show the entered pack-list-items on the page

### ISSUE THREAD

**Issue by JoaLehma** [JoaLehma/capstone-project#1]
**As a** user
**I want to** I want to add items to my packing list
**So that** so that I have an overview of all the things I want to pack
# Description

![Bildschirmfoto 2022-08-15 um 16 46 56](https://user-images.githubusercontent.com/107816788/184658007-9043ddfb-7c1e-4978-8ca0-fbc13b1169cd.png)

# Acceptance Criteria

- [x] An input field for the items name is displayed (label: "Item")
- [x] a submit button is displayed
- [x] The input field is required and have minimal input lenght of "3"
- [x] After submitting the input is displayed in a list of added items on the page
- [x] The input field is cleared after submit
- [x] There is a Headline "just pack" shown on the page

# Tasks

(for developers team)

- [x] Create a new branch
- [x] Create a form component with one input field
- [x] Add a submit button to the form
- [x] Add event.preventDefault() to the form submit
- [x] Create form validations
- [x] Render the input as a list item to the page 
- [x] Add state handling (with zustand.js)

# Complexity

L

**Comment by alexclaes** [comment]
Hi Joachim,

nice and concise user story!

There is one thing you should change: Don't yet implement the checkbox, as it doesn't have any functionality as of now.

Please remember no empty pages, no placeholders for further implementation, no buttons without functions.

In addition you should make clear in the acceptance criteria, that a list of added items will be displayed (not just the last added item)

**Comment by ahohnsen** [comment]
Hey Joachim,

Nice job 💪🏼 I have some additional comments:

- In your scribble it looks like as you have entered developer information in the input field _(input field text, required, min length)_. I would suggest to only show in the scribble how the app should look like for a user later on and to add this information to your acceptance criteria. 
- In your acceptance criteria you do not need to write what is already visible in the scribble (e.g. An input field for the items name is displayed (label: "Item"))
- I would suggest rephrasing the value proposition. The user does not really want to have a form, the user wants to be able to add items to a list 🙂:

_As a user
I want to add items to my packing list
so that I have an overview of all the things I want to pack_
