### ISSUE TITLE
Create a Login-Page

### ISSUE THREAD

**Issue by JoaLehma** [JoaLehma/capstone-project#11]
**As a** user
**I want to** to have the possibility to work together with others on a packing list
**So that** we only need one common list and can work through it together

# Acceptance Criteria

- [x] There is a Login-Page
- [x] You need a Github-Account for the Login

# Tasks

- [x] Create a new branch
- [x] Add NextAuth
- [x] After Login get redirected to the main page
- [x] Route the app based on Auth

# Complexity

L
