### ISSUE TITLE
Add Category-Cards

### ISSUE THREAD

**Issue by JoaLehma** [JoaLehma/capstone-project#13]
**As a** user
**I want to** be able to access saved item-collections
**So that** i can quickly and individually compile my packing list

![Bildschirmfoto 2022-09-02 um 14 40 55](https://user-images.githubusercontent.com/107816788/188147815-58294b45-c2e3-4aec-8aea-37c3264a2ba6.png)

# Acceptance Criteria

- [x] There is a Input-Field to create the item-cards on the main page
- [x] The Cards are rendered to the page 
- [x] The Cards have 3 Buttons. "Add items",  "Bookmark" and "Delete"
- [x] When i click on "Add items" another inputfield appears where i can add items to the Card
- [x] There is a home button to go back to the main page
- [x] Click on the delete button, deletes the Card
- [x] Click the Bookmark-Button renders the card with its items to the packlist page
- [x] There is a navigation to switch between main and packlist page
- [ ] There is a clear-button on the packlist page. Click the button removes the bookmark and set all checked items back to false 

# Tasks

- [x] Create a new branch
- [x] Create A Card-Component with the Buttons
- [x] Update the models for MongoDB
- [x] Add a function for the bookmark-button
- [ ] Add a function for the clear-button
- [x] Add a nav

# Complexity

XL
