### ISSUE TITLE
Add a checkbox to each item

### ISSUE THREAD

**Issue by JoaLehma** [JoaLehma/capstone-project#3]
**As a** user
**I want to** be able to check off items
**So that** I know what I have already packed
# Description

![Bildschirmfoto 2022-08-18 um 14 13 10](https://user-images.githubusercontent.com/107816788/185392100-ff62c3d7-9fe7-43b4-b439-19a6a27955f6.png)

# Acceptance Criteria

- [x] There is a checkbox in front of each item
- [x] After the checkbox is clicked, the item is grayed out and moves to the bottom of the list
- [x] Uncheck the box, and the item color is black again and moves to the top of the list

# Tasks

(for developers team)

- [x] Create a new branch
- [x] Render the items into a checkbox list
- [x] Add a function to reorder the list on click

# Complexity

M

**Comment by ahohnsen** [comment]
Hey Joachim,

Nice job. 🚀 

I think you have a typo in your value proposition:

> As a user
> I want to ~~I would like to~~ be able to check off items
> So that I know what I have already packed

As well I think it is nicer to always see the whole screen/app in the scribble instead of only a small part of it 🙂 Then it is easier to see how everything is supposed to look like after your user story is finished.
