### ISSUE TITLE
Add an delete button to the list items

### ISSUE THREAD

**Issue by JoaLehma** [JoaLehma/capstone-project#5]
**As a** user
**I want to** have an delete button 
**So that** i can delete items that i no longer need

# Description

![Bildschirmfoto 2022-08-18 um 14 55 27](https://user-images.githubusercontent.com/107816788/185399957-b9b013a6-7c92-4ef1-ba0c-e8d2584e814c.png)

# Acceptance Criteria

- [ ] there is a delete button behind the items
- [ ] clicking the button deletes the item

# Tasks

(for developers team)

- [ ] Create new branch
- [ ] Add an button to the list items
- [ ] Create a delete function on button click

# Complexity

S

**Comment by tsimvris** [comment]
Hi @JoaLehma , 

looks nice 🥇 .

Only one minor tip:

> So that i can delete items that i no longer need or contain spelling errors

I would suggest that you delete the "or contain spelling errors" cause this is a case for an edit button and not a delete button

**Comment by JoaLehma** [comment]
Thx @tsimvris
Allready updated! :)
