### ISSUE TITLE
Create a Database Connection to MongoDb

### ISSUE THREAD

**Issue by JoaLehma** [JoaLehma/capstone-project#7]
**As a** developer
**I want to** have a database connection,
**So that** multiple users can work together on a packing list

# Acceptance Criteria

- [ ] When i submit an item via the inputfield, it is stored in the mongoDB database and rendered to the page

# Tasks

(for developers team)

- [x] Create a new branch
- [x] npm i mongoose
- [x] Create a new MongoDB database
  - [x] Create .env.local with the URL and the database name 
  - [x] Create dbConnect for the connection to the database
- [x] Create a Model
- [x] Create Services
- [x] Create an API

# Complexity

XL
