### ISSUE TITLE
Create delete Button and checkbox functionality

### ISSUE THREAD

**Issue by JoaLehma** [JoaLehma/capstone-project#8]
**As a** developer
**I want to** have the same functions with mongoDB as before local
**So that** the user have the same user-experience than before

# Acceptance Criteria

- [x] There is a delete button behind the items
- [x] After the checkbox is clicked, the item is grayed out and moves to the bottom of the list
- [x] Uncheck the box, and the item color is black again and moves to the top of the list

# Tasks

- [x] Create a new branch
- [x] Add a function to reorder the list on click
- [x] Add an button to the list items
- [x] Create a delete function on button click

# Complexity

L

**Comment by ckskr** [comment]
Dear JoaLehma, 
I think this user story should be written from a user point of view. 
Furthermore to have a little less complex user story you could split the delete function and the checked functionality. So it is easier for you and faster in the review. 
I would strongly recommend to think about it. Happy to discuss further
